### ISSUE TITLE
怎样禁止循环？

### ISSUE THREAD

**Issue by Achenglove** [Vegen/VRecyclerViewBanner#1]

**Comment by Vegen** [comment]
试下设置属性 app:autoPlaying="false"

**Comment by Vegen** [comment]
或者调用 .setAutoPlaying(false); 方法 @Achenglove

**Comment by Achenglove** [comment]
这个方法只是禁止自动播放而已，我是想禁止循环滑动，也就是滑动到最后一张就不能再滑动

**Comment by Vegen** [comment]
我增加了 是否开启无限循环的属性 infinite 和方法 setInfinite(boolean infinite)，由于更新版本墙内有些问题，你暂时可以下载源码再集成。感谢反馈 @Achenglove

**Comment by Vegen** [comment]
v1.2.0 已更新，欢迎继续反馈问题。
